# Generated by Django 6.0.2 on 2026-07-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mise_en_relation', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('autre', 'Autre')], max_length=20)),
                ('statut_transaction', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestes_effectues', to='utilisateurs.utilisateur')),
                ('mise_en_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestes', to='mise_en_relation.miseenrelation')),
            ],
            options={
                'verbose_name': 'Geste',
                'verbose_name_plural': 'Gestes',
            },
        ),
    ]
