# Generated by Django 5.2.16 on 2026-07-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseEnRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notification_whatsapp_envoyee', models.BooleanField(default=False)),
                ('confirmation_declarant', models.BooleanField(default=False)),
                ('confirmation_beneficiaire', models.BooleanField(default=False)),
                ('cloture_administrateur', models.BooleanField(default=False)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField()),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mise_en_relation', to='annonces.annonce')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_en_relation', to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Mise en relation',
                'verbose_name_plural': 'Mises en relation',
            },
        ),
    ]
