# Generated by Django 5.2.16 on 2026-07-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mise_en_relation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miseenrelation',
            name='confirmation_declarant',
        ),
    ]
