# Generated by Django 6.0.2 on 2026-07-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_action', models.CharField(choices=[('publication', 'Publication'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('consultation', 'Consultation'), ('restitution', 'Restitution'), ('geste', 'Geste financier'), ('inscription', 'Inscription'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_actions', to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historique',
                'ordering': ['-date_creation'],
            },
        ),
    ]
