# Generated by Django 5.2.16 on 2026-07-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='type_action',
            field=models.CharField(choices=[('publication', 'Publication'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('consultation', 'Consultation'), ('restitution', 'Restitution'), ('inscription', 'Inscription'), ('autre', 'Autre')], max_length=20),
        ),
    ]
