# Generated by Django 5.2.16 on 2026-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('telephone', models.CharField(help_text='Identifiant du compte, doit être unique.', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ville', models.CharField(blank=True, help_text='Obligatoire uniquement pour publier une annonce.', max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, help_text='Obligatoire uniquement pour publier une annonce.', max_length=100, null=True)),
                ('est_actif', models.BooleanField(default=True, help_text="Permet à l'administrateur de suspendre un compte.")),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
