# Generated by Django 5.2.16 on 2026-07-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom_recherche', models.CharField(max_length=100)),
                ('prenom_recherche', models.CharField(max_length=100)),
                ('notifie', models.BooleanField(default=False, help_text='Indique si une notification WhatsApp a déjà été envoyée.')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_recherche', to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte de recherche',
                'verbose_name_plural': 'Alertes de recherche',
            },
        ),
    ]
