# Generated by Django 5.2.16 on 2026-07-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('photo_recto', models.ImageField(upload_to='cni/recto/')),
                ('photo_verso', models.ImageField(upload_to='cni/verso/')),
                ('nom_titulaire', models.CharField(max_length=100)),
                ('prenom_titulaire', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('numero_carte', models.CharField(max_length=50)),
                ('photo_titulaire', models.ImageField(upload_to='cni/titulaire/')),
                ('position_cni', models.CharField(choices=[('possession', 'En ma possession'), ('commissariat', 'Commissariat'), ('mairie', 'Mairie'), ('autre', 'Autre lieu')], max_length=20)),
                ('position_precision', models.CharField(blank=True, help_text="Obligatoire uniquement si position_cni = 'Autre lieu'.", max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('publiee', 'Publiée'), ('en_cours', 'En cours de restitution'), ('restituee', 'Restituée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('motif_rejet', models.CharField(blank=True, max_length=255, null=True)),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_publiees', to='utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
    ]
