# Generated by Django 5.2.16 on 2026-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_position_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='position_precision',
            field=models.CharField(blank=True, help_text="Obligatoire uniquement si position_cni = 'Autre lieu'.", max_length=255, null=True),
        ),
    ]
